name: Build & Deploy ChatAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Build project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # 5️⃣ Publish project
      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      # 6️⃣ Copy published files to VM
      - name: Copy published build to VM
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          source: "./publish/*"
          target: "~/ChatAPI"
          strip_components: 1

      # 7️⃣ Copy source code (for migrations) to VM
      - name: Copy project source to VM
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          source: "./"
          target: "~/ChatAPI_Source"
          exclude: |
            **/bin/**
            **/obj/**
            .git/**

      # 8️⃣ Run EF migrations and restart systemd service
      - name: Run migrations & restart ChatAPI
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            # Add dotnet tools to PATH
            export PATH="$PATH:$HOME/.dotnet/tools"

            # Set environment variables for migrations
            export ConnectionStrings__Default="${{ secrets.DB_ORACLE_CONNECTION }}"
            export Jwt__Key="${{ secrets.JWT_KEY }}"

            echo "Running EF migrations..."
            cd ~/ChatAPI_Source/ChatAPI
            dotnet ef database update --no-build --project ./ChatAPI.csproj

            echo "Restarting ChatAPI systemd service..."
            sudo systemctl daemon-reload
            sudo systemctl restart chatapi
            sudo systemctl status chatapi --no-pager
