name: Deploy to Oracle VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # 3️⃣ Publish the project
      - name: Publish .NET Project
        run: dotnet publish -c Release -o ./publish

      # 4️⃣ Ensure target directory exists on VM
      - name: Ensure target directory exists
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/ChatAPI

      # 5️⃣ Stop service before deploying
      - name: Stop service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop ChatAPI || true

      # 6️⃣ Clean old files
      - name: Clean old files
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/ChatAPI/*

      # 7️⃣ Upload published build to VM
      - name: Upload new build
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          source: "./publish/*"
          target: "/home/ubuntu/ChatAPI"
          strip_components: 1

      # 8️⃣ Set environment variables on VM
      - name: Update environment variables
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            echo "ConnectionStrings__DefaultConnection=${{ secrets.DB_Oracle_CONNECTION }}" | sudo tee -a /etc/environment
            echo "Jwt__Key=${{ secrets.JWT_KEY }}" | sudo tee -a /etc/environment
            source /etc/environment

      # 9️⃣ Run EF Core migrations
      - name: Run EF Core migrations
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/ChatAPI
            export ConnectionStrings__DefaultConnection="${{ secrets.DB_Oracle_CONNECTION }}"
            export Jwt__Key="${{ secrets.JWT_KEY }}"
            dotnet ef database update --no-build --project /home/ubuntu/ChatAPI/ChatAPI.csproj

      # 🔟 Restart the service
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl start ChatAPI
            sudo systemctl status ChatAPI --no-pager
